spring:
  datasource:
    url: jdbc:h2:file:./data/forum-local;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  cache:
    type: simple
  session:
    store-type: none
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 58081

logging:
  level:
    root: INFO
    com.xzy.forum: INFO
